/**
 * Seed data only — brand/model catalog (seed pack v2).
 * Applied once per database by the versioned seed (see ../seed.ts). Never edit a shipped
 * pack to "fix" data on existing installs: add a new pack instead.
 *
 * Only well-known brands are included. Models are listed only for the major ones (roughly the
 * last 5 years); every other brand is added without models and the shop adds models from
 * Settings as needed.
 */
export interface CatalogBrand {
  name: string
  models?: string[]
}

export const BRAND_CATALOG_V2: CatalogBrand[] = [
  {
    name: 'Samsung',
    models: [
      'Galaxy A02',
      'Galaxy A03',
      'Galaxy A03 Core',
      'Galaxy A04e',
      'Galaxy A04s',
      'Galaxy A05',
      'Galaxy A05s',
      'Galaxy A06',
      'Galaxy A12',
      'Galaxy A13',
      'Galaxy A15',
      'Galaxy A16',
      'Galaxy A22',
      'Galaxy A23',
      'Galaxy A25',
      'Galaxy A32',
      'Galaxy A33',
      'Galaxy A35',
      'Galaxy A52',
      'Galaxy A52s',
      'Galaxy A53',
      'Galaxy A72',
      'Galaxy A73',
      'Galaxy M12',
      'Galaxy M13',
      'Galaxy M14',
      'Galaxy M15',
      'Galaxy M23',
      'Galaxy M33',
      'Galaxy M34',
      'Galaxy M54',
      'Galaxy S21+',
      'Galaxy S21 Ultra',
      'Galaxy S21 FE',
      'Galaxy S22+',
      'Galaxy S22 Ultra',
      'Galaxy S23+',
      'Galaxy S23 Ultra',
      'Galaxy S23 FE',
      'Galaxy S24',
      'Galaxy S24+',
      'Galaxy S25',
      'Galaxy S25 Ultra',
      'Galaxy Z Flip 3',
      'Galaxy Z Flip 4',
      'Galaxy Z Flip 5',
      'Galaxy Z Fold 3',
      'Galaxy Z Fold 4',
      'Galaxy Z Fold 5',
      'Galaxy Note 20 Ultra'
    ]
  },
  {
    name: 'Xiaomi',
    models: [
      'Mi 10T',
      'Mi 11 Lite',
      'Mi 11T',
      'Mi 11T Pro',
      'Xiaomi 12',
      'Xiaomi 12 Lite',
      'Xiaomi 12T',
      'Xiaomi 12T Pro',
      'Xiaomi 13',
      'Xiaomi 13 Lite',
      'Xiaomi 13T',
      'Xiaomi 13T Pro',
      'Xiaomi 14',
      'Xiaomi 14T',
      'Xiaomi 14 Ultra'
    ]
  },
  {
    name: 'Redmi',
    models: [
      'Redmi 9',
      'Redmi 9A',
      'Redmi 9C',
      'Redmi 9T',
      'Redmi 10',
      'Redmi 10A',
      'Redmi 10C',
      'Redmi 12',
      'Redmi 12C',
      'Redmi 13',
      'Redmi 13C',
      'Redmi A1',
      'Redmi A2',
      'Redmi A3',
      'Redmi Note 9',
      'Redmi Note 9 Pro',
      'Redmi Note 10',
      'Redmi Note 10 Pro',
      'Redmi Note 10S',
      'Redmi Note 11',
      'Redmi Note 11 Pro',
      'Redmi Note 11S',
      'Redmi Note 12',
      'Redmi Note 12 Pro',
      'Redmi Note 12S',
      'Redmi Note 13',
      'Redmi Note 13 Pro',
      'Redmi Note 13 Pro+',
      'Redmi Note 14'
    ]
  },
  {
    name: 'Poco',
    models: [
      'Poco X3 NFC',
      'Poco X3 Pro',
      'Poco X4 Pro',
      'Poco X5',
      'Poco X5 Pro',
      'Poco X6',
      'Poco X6 Pro',
      'Poco F3',
      'Poco F4',
      'Poco F5',
      'Poco F5 Pro',
      'Poco F6',
      'Poco M4 Pro',
      'Poco M5',
      'Poco M6 Pro',
      'Poco C40',
      'Poco C55',
      'Poco C65'
    ]
  },
  {
    name: 'Oppo',
    models: [
      'A15',
      'A18',
      'A38',
      'A57',
      'A74',
      'A79',
      'A96',
      'Reno 5',
      'Reno 7',
      'Reno 8T',
      'Reno 11',
      'Reno 12',
      'Find X3 Pro',
      'Find X5 Pro',
      'Find X6 Pro'
    ]
  },
  {
    name: 'Realme',
    models: [
      'C15',
      'C20',
      'C21Y',
      'C25',
      'C25Y',
      'C30',
      'C31',
      'C51',
      'C61',
      'C63',
      'C65',
      'Realme 8',
      'Realme 8 Pro',
      'Realme 9 Pro',
      'Realme 9i',
      'Realme 10',
      'Realme 10 Pro',
      'Realme 11',
      'Realme 12 Pro',
      'GT Neo 3',
      'GT 5',
      'Narzo 50',
      'Narzo 60'
    ]
  },
  {
    name: 'Infinix',
    models: [
      'Smart 5',
      'Smart 6',
      'Smart 7',
      'Smart 8',
      'Smart 9',
      'Hot 10',
      'Hot 10 Play',
      'Hot 11',
      'Hot 11S',
      'Hot 12',
      'Hot 12 Play',
      'Hot 20',
      'Hot 30',
      'Hot 30i',
      'Hot 40',
      'Hot 40 Pro',
      'Note 10',
      'Note 11',
      'Note 12',
      'Note 30',
      'Note 40',
      'Zero 5G',
      'Zero 30'
    ]
  },
  {
    name: 'Tecno',
    models: [
      'Spark 6',
      'Spark 7',
      'Spark 8',
      'Spark 8C',
      'Spark 9',
      'Spark 10',
      'Spark 10 Pro',
      'Spark 20',
      'Spark 20 Pro',
      'Spark Go',
      'Camon 16',
      'Camon 17',
      'Camon 18',
      'Camon 19',
      'Camon 20',
      'Camon 30',
      'Pop 5',
      'Pop 6',
      'Pop 7',
      'Pop 8',
      'Pova 3',
      'Pova 4',
      'Pova 5',
      'Phantom X2'
    ]
  },
  {
    name: 'Itel',
    models: ['A48', 'A49', 'A56', 'A58', 'A60', 'A70', 'P38', 'P40', 'P55', 'S18', 'S23', 'Vision 1', 'Vision 3']
  },
  {
    name: 'Huawei',
    models: [
      'Y5',
      'Y6',
      'Y6p',
      'Y7 Prime',
      'Y7a',
      'Y9 Prime',
      'Y9a',
      'Y9s',
      'Nova 5T',
      'Nova 7i',
      'Nova 8i',
      'Nova 9 SE',
      'Nova 11',
      'Nova 11i',
      'P20 Lite',
      'P30',
      'P30 Pro',
      'P40',
      'P40 Lite',
      'P50',
      'Mate 20',
      'Mate 30',
      'Mate 40 Pro'
    ]
  },
  {
    name: 'Honor',
    models: [
      'Honor X6',
      'Honor X6a',
      'Honor X7',
      'Honor X7a',
      'Honor X8',
      'Honor X8a',
      'Honor X9',
      'Honor X9a',
      'Honor X9b',
      'Honor 50',
      'Honor 70',
      'Honor 90 Lite',
      'Honor Magic 5',
      'Honor Magic 6',
      'Honor 200'
    ]
  },

  // Brands below are added without models (the shop adds models as needed)
  { name: 'OnePlus' },
  { name: 'Motorola' },
  { name: 'Nokia' },
  { name: 'Google Pixel' },
  { name: 'Sony' },
  { name: 'LG' },
  { name: 'HTC' },
  { name: 'Asus' },
  { name: 'Lenovo' },
  { name: 'Alcatel' },
  { name: 'TCL' },
  { name: 'ZTE' },
  { name: 'Nothing' },
  { name: 'Meizu' }
]
